### ISSUE TITLE
How to use macroboard?

### ISSUE THREAD

**Issue by aplatypus** [Moxinilian/macroboard#1]
@Moxinilian ... I found the description for `macroboard` in passing and saw that it works with Wayland.  I need and `xdotool` replacement that can work under Wayland to issue some keystrokes (command lines and inputs).

* Do you think `macroboard` is suitable for this?
* I am also looking for some notes or a blog on how to used the crate?
  * I built and ran the example program `basic.rs`, nothing happened.
  * I would expect there to be some kind of macro definition input or such??

I hope you can point me in the right direction please?  (I am using Kubuntu 23.04)  Thanks in advance.

**Comment by Moxinilian** [comment]
Hey!

Macroboard is more of a library than a standalone tool. It's focused on getting input from the external keyboard more than actually doing actions. You're expected to implement the actions yourself.

For example, in the basic.rs example, triggering a key only prints stuff to the console. It's then on you to implement logic that does whatever you want it to do.

If that sounds good to you, check out [the documentation on docs.rs](https://docs.rs/macroboard/latest/macroboard/), it should explain everything. The crate is quite small so it should not be too overwhelming.

**Comment by aplatypus** [comment]
Ah, thanks for that info.  Probably not what I'm looking for just now.  Will review the docs :-)
